apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment
  labels:
    app: spring-boot-k8-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-k8-sample
  template:
    metadata:
      labels:
        app: spring-boot-k8-sample
    spec:
      containers:
        - name: spring-boot-k8-sample
          image: swap2vijay/springboot-rest-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always


apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-sample-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-k8s
